kind: Deployment
apiversion: apps/v1
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
    project: helm-expense
spec:
  replicas: {{ .Values.Deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      project: helm-expense
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        project: helm-expense
    spec:
      containers:
        - name: nginx
          image: {{ .Values.Deployment.image }}
          ports:
            - containerPort: 80